logging:
  loggers:
      "org.mayocat": DEBUG

dataSource:
  name: "datanucleus"
  properties:
    javax.jdo.PersistenceManagerFactoryClass: org.datanucleus.api.jdo.JDOPersistenceManagerFactory
    javax.jdo.option.ConnectionURL: jdbc:hsqldb:mem:mayocat
    javax.jdo.option.ConnectionUserName: sa
    javax.jdo.option.ConnectionPassword: 
    datanucleus.autoCreateSchema: true
    datanucleus.validateTables: false
    datanucleus.validateConstraints: false
    datanucleus.ConnectionDriverName: org.hsqldb.jdbc.JDBCDriver
