logging:
  loggers:
      "org.mayocat": DEBUG
      #"DataNucleus.Datastore.Native": DEBUG
      #"DataNucleus.Datastore.Schema": DEBUG
      #"DataNucleus.Plugin": DEBUG
      #"DataNucleus.Connection": DEBUG
      #"DataNucleus.SchemaTool": DEBUG

  file:
    archive: false

multitenancy:
  activated: false
  defaultTenant: shop

authentication:
  cookieEncryptionKey: Change me here!

dataSource:
  name: "datanucleus"
  properties:
    javax.jdo.option.ConnectionDriverName: com.mysql.jdbc.Driver
    javax.jdo.option.ConnectionURL: jdbc:mysql://127.0.0.1/shop
    javax.jdo.option.ConnectionUserName: root
    javax.jdo.option.ConnectionPassword:
    datanucleus.connectionPoolingType: DBCP
    datanucleus.connectionPool.maxIdle: 10
    datanucleus.connectionPool.minIdle: 3
    datanucleus.connectionPool.maxActive: 5
    datanucleus.connectionPool.maxWait: 60
    datanucleus.connectionPool.maxStatements: 20
    datanucleus.connectionPool.testSQL: SELECT 1
    datanucleus.connectionPool.timeBetweenEvictionRunsMillis: 2400000
    datanucleus.connectionPool.minEvictableIdleTimeMillis: 18000000
