logging:
  loggers:
      "org.mayocat": DEBUG
  file:
    archive: false

dataSource:
  name: "datanucleus"
  properties:
    javax.jdo.option.ConnectionDriverName: org.hsqldb.jdbc.JDBCDriver
    javax.jdo.option.ConnectionURL: jdbc:hsqldb:mem:mayocat
    javax.jdo.option.ConnectionUserName: sa
    javax.jdo.option.ConnectionPassword: 
