logging:
  loggers:
      "org.mayocat": DEBUG

  file:
    archive: false

multitenancy:
  activated: false
  defaultTenant: shop

authentication:
  cookieEncryptionKey: Change me here!

dataSource:
  name: "jdbi"

database:
  driverClass: com.mysql.jdbc.Driver
  user: root
  password: 
  url: jdbc:mysql://127.0.0.1/shop
  properties:
    charSet: UTF-8
  maxWaitForConnection: 1s
  validationQuery: "/* MayocatShop Health Check */ SELECT 1"
  minSize: 8
  maxSize: 32
  checkConnectionWhileIdle: false
  checkConnectionHealthWhenIdleFor: 10s
  closeConnectionIfIdleFor: 1 minute

shop:
  products:
    categories:
      enabled: true
      configurable: true

#    variants:
#      enabled: true
#      mandatory: false
#      priceVaries: true
#      configurable: false
